---
- hosts: all
  become: yes

  tasks:
    - name: Install Docker
      yum: name=docker state=latest
      tags: docker

    - name: Start docker
      service: name=docker state=started

    - name: install compose file
      copy: src=files/docker/mysqlwordpress.yml dest=/usr/bin/mysqlwordpress.yml owner=root group=root mode=0644

    - name: install pip
      yum: name=python27-pip.noarch

    - name: Install pip packages
      pip: name={{ item }}
      with_items:
        - docker-py
        - awscli
        - docker-compose

    - name: Start Compose
      command: /usr/local/bin/docker-compose -f /usr/bin/mysqlwordpress.yml up -d